# AOC 2015 Day 25 ----
# Let It Snow ---

# Part 1 ----
# To continue, please consult the code grid in the manual.  Enter the code at row 2981, column 3075.

# Create a matrix like below first
#   |  1   2   3   4   5   6  
# ---+---+---+---+---+---+---+
# 1 |  1   3   6  10  15  21
# 2 |  2   5   9  14  20
# 3 |  4   8  13  19
# 4 |  7  12  18
# 5 | 11  17
# 6 | 16

#   |    1         2         3         4         5         6
# ---+---------+---------+---------+---------+---------+---------+
# 1 | 20151125  18749137  17289845  30943339  10071777  33511524
# 2 | 31916031  21629792  16929656   7726640  15514188   4041754
# 3 | 16080970   8057251   1601130   7981243  11661866  16474243
# 4 | 24592653  32451966  21345942   9380097  10600672  31527494
# 5 |    77061  17552253  28094349   6899651   9250759  31663883
# 6 | 33071741   6796745  25397450  24659492   1534922  27995004

# The first code is 20151125. After that, each code is generated by taking the previous one, 
# multiplying it by 252533, and then keeping the remainder from dividing that value by 33554393.

library(dplyr)
library(stringr)

value <- 20151125.

# Start at (1,1) position
x <- 1
y <- 1

repeat {
  if (x == 1) {
    x <- y + 1
    y <- 1
    # print(paste0("x ", x))
    # print(paste0("y ", y))
  } else {
    x <- x - 1
    y <- y + 1
    # print(paste0("x ", x))
    # print(paste0("y ", y))
  }
  
  value <- (value * 252533) %% 33554393
  
  # print(paste0("x ", x, " y ", y, " value ", value))
  
  # Break when you reach puzzle input 
  if (x == 2981 & y == 3075) break
  
}

cat("Please consult the code grid in the manual. Enter the code at row 2981, column 3075: ", value)
